name = "QuackIO"
uuid = "7b8617ff-c43a-4c37-a28b-ad5a1791f8ae"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.1"

[deps]
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
DuckDB = "1.0.0"
Tables = "1.12.0"
julia = "1.9"
